
modLoader="javafml" 
loaderVersion="[37,)" 
license="All rights reserved"

[[mods]]
modId="potsnstuff"

version="1.0" 
displayName="Pots 'n' Stuff" 
logoFile="icon.png" 
authors="MrClassyfied" 
description='''
A bunch of new potions, two new potion bottles and a new potion bag.
'''
[[dependencies.potsnstuff]]
     modId="forge"
     mandatory=true 
    versionRange="[37,)" 
    ordering="NONE"
    side="BOTH"
    
[[dependencies.potsnstuff]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.1,1.19)"
    ordering="NONE"
    side="BOTH"
